dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/
    - .tox

language: python
python:
  - 3.6
  - 3.7

notifications:
  email: false

install:
  - pip install -U 'setuptools > 36' && pip install tox-travis
  - pip install coveralls

script:
  - tox

after_script:
  - coveralls
