dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/.cache/pip
    - .tox/

language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

notifications:
  email: false

install:
  - pip install -U 'setuptools > 36' && pip install tox-travis
  - pip install coveralls
  - mkdir $HOME/.eeweather
  - zcat $TRAVIS_BUILD_DIR/thermostat/resources/cache.sql.gz | sqlite3 $HOME/.eeweather/cache.db

script:
  - tox

after_script:
  - coveralls
