sudo: false

cache:
  directories:
    - $HOME/.pip-cache/
    - .tox

language: python
#python:
  #- 2.7
  #- 3.4
  #- 3.5
  #- 3.6

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

notifications:
  email: false

install:
  - pip install tox-travis
  - pip install coveralls

script:
  - tox

after_script:
  - coveralls
