[tox]
envlist = clean,py{311,312,313,314},report

[pytest]
testpaths = tests
addopts =
    --cov-report=term-missing --cov=thermostat --cov-append -x

[testenv]
deps =
    pytest
    pytest-cov
commands =
     pytest {posargs:-vv} 

depends =
    {py311,py312,py313,py314}: clean
    report: py311,py312,py313,py314

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage html
    coverage report

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[coverage:run]
parallel=True
data_suffix=True
