#!/bin/bash
CONTAINER=epathermostat
lxc stop $CONTAINER
lxc delete $CONTAINER
lxc launch ubuntu:20.04 $CONTAINER -c security.privileged=true
sleep 3
lxc config device add $CONTAINER homedir disk source=/home/craig/projects/epathermostat path=/home/ubuntu/epathermostat
sleep 3
lxc exec $CONTAINER -- sudo add-apt-repository ppa:deadsnakes/ppa -y
lxc exec $CONTAINER -- sudo apt install -y \
    build-essential sqlite3 \
    python3.10 python3.10-dev python3.10-venv \
    python3.9 python3.9-dev python3.9-venv \
    python3.8 python3.8-dev python3.8-venv \
    python3.7 python3.7-dev python3.7-venv \
    python3.6 python3.6-dev python3.6-venv
lxc exec $CONTAINER -- sudo chown ubuntu /home/ubuntu
lxc exec $CONTAINER -- sudo --login --user ubuntu /usr/bin/python3.9 -m venv /home/ubuntu/venv
lxc exec $CONTAINER -- sudo --login --user ubuntu /home/ubuntu/venv/bin/pip install -r /home/ubuntu/epathermostat/dev-requirements.txt
lxc exec $CONTAINER -- sudo --login --user ubuntu mkdir /home/ubuntu/.eeweather
lxc exec $CONTAINER -- sudo --login --user ubuntu bash -c "zcat /home/ubuntu/epathermostat/thermostat/resources/cache.sql.gz | sqlite3 /home/ubuntu/.eeweather/cache.db"
