import logging
import json
from datetime import date
from importlib.resources import files

from eeweather import WeatherLocation, WeatherStation
from eeweather.exceptions import UnrecognizedPlaceError

logging.getLogger(__name__)

# Static JSON fallback map (generated by scripts/build_station_data.py build-lookup).
zipcode_usaf_json = (files('thermostat.resources') / 'zipcode_usaf_station.json').read_text()
zipcode_usaf = json.loads(zipcode_usaf_json)

# Maximum distance (km) from ZCTA centroid to assigned station.
_MAX_STATION_DISTANCE_KM = 500


def get_closest_station_by_zipcode(zipcode, required_years=None):
    """Return the nearest weather station for a ZIP code / ZCTA whose GHCNh
    record covers the years being analysed.

    Ranks the ZCTA's candidate GHCNh stations by distance (within 500 km of the
    ZCTA centroid) and selects the nearest whose registry inventory covers every
    year in *required_years*. Falls back to the static JSON map when eeweather
    does not recognise the ZCTA or no qualifying station is found in range.

    Parameters
    ----------
    zipcode : string
        5-digit ZIP code or ZCTA.
    required_years : list of int, optional
        Calendar years the station must have data for. Callers running
        historical data should pass the years spanned by that data so station
        selection matches the analysed period rather than the current calendar
        year. Defaults to [today.year-1, today.year] when not supplied.

    Returns
    -------
    station : string or None
        USAF station ID, or None if no station could be determined.
    """
    if required_years is None:
        today = date.today()
        required_years = [today.year - 1, today.year]

    try:
        location = WeatherLocation.from_place(
            "zcta", zipcode.zfill(5), sources=("ghcnh",)
        )
    except UnrecognizedPlaceError:
        logging.warning("Unrecognized ZCTA %s — falling back to JSON map.", zipcode)
        return lookup_usaf_station_by_zipcode(zipcode)

    # Distance-ranked GHCNh candidates within the cap. Ranking (distance, then
    # quality) and the distance cap are native to rank_stations now, so the
    # hand-rolled QUALITY_SORT/re-sort is gone.
    candidates = location.candidates(
        has_sources=("ghcnh",),
        max_distance_meters=_MAX_STATION_DISTANCE_KM * 1000.0,
    )

    for station_id, _row in candidates.iterrows():
        station = WeatherStation(station_id)
        inventory = station.inventory_years.get("ghcnh")
        if not inventory:
            continue
        first, last = inventory
        # Registry inventory replaces probing a primed cache for
        # 'isd-hourly-{usaf}-{year}' keys.
        if all(first <= y <= last for y in required_years):
            usaf_ids = station.ids.get("usaf") or ()
            usaf = usaf_ids[0] if usaf_ids else None
            if usaf and not str(usaf).startswith("A"):  # skip Canadian airport codes
                return usaf

    logging.warning(
        "No station with data for %s within %d km of zipcode %s — "
        "falling back to JSON map.",
        required_years, _MAX_STATION_DISTANCE_KM, zipcode,
    )
    return lookup_usaf_station_by_zipcode(zipcode)


def lookup_usaf_station_by_zipcode(zipcode):
    """Static JSON map lookup (fallback method).

    Parameters
    ----------
    zipcode : string

    Returns
    -------
    station : string or None
    """
    return zipcode_usaf.get(zipcode, None)
