name: Windows Testing

on: [push]

jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # Apparently 3.10 gets converted to 3.1 if it's not a string. Brilliant.
        python-version: [3.8]


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Test with pytest
      run: |
        # Activate the base environment
        python --version
        C:\Miniconda\condabin\conda.bat activate base
        python --version
        C:\Miniconda\condabin\conda.bat install pytest pytest-cov coverage mock pip
        python --version
        C:\Miniconda\condabin\conda.bat install -c conda-forge shapely
        python --version
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pytest --cov-report=term-missing --cov=thermostat